/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.adrisilva.calculadora.view;

import java.util.regex.Pattern;
import javax.swing.JButton;
import br.com.adrisilva.calculadora.classes.Operations;


/**
 *
 * @author Familía
 */
public class ViewCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ViewCalculator
     */
    private boolean fimDoCalculo = false;

    public ViewCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        btnAddZero = new javax.swing.JButton();
        btnAddOne = new javax.swing.JButton();
        btnAddFour = new javax.swing.JButton();
        btnAddSeven = new javax.swing.JButton();
        btnAddTwo = new javax.swing.JButton();
        btnAddFive = new javax.swing.JButton();
        btnAddEight = new javax.swing.JButton();
        btnAddThree = new javax.swing.JButton();
        btnAddSix = new javax.swing.JButton();
        btnAddNine = new javax.swing.JButton();
        btnAddComma = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Java");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        txtResult.setEditable(false);
        txtResult.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtResult.setText("0");
        txtResult.setToolTipText("");
        txtResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResultKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResult)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        btnAddZero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddZero.setText("0");
        btnAddZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddZeroActionPerformed(evt);
            }
        });

        btnAddOne.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddOne.setText("1");
        btnAddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOneActionPerformed(evt);
            }
        });

        btnAddFour.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddFour.setText("4");
        btnAddFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFourActionPerformed(evt);
            }
        });

        btnAddSeven.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddSeven.setText("7");
        btnAddSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSevenActionPerformed(evt);
            }
        });

        btnAddTwo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddTwo.setText("2");
        btnAddTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTwoActionPerformed(evt);
            }
        });

        btnAddFive.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddFive.setText("5");
        btnAddFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFiveActionPerformed(evt);
            }
        });

        btnAddEight.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddEight.setText("8");
        btnAddEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEightActionPerformed(evt);
            }
        });

        btnAddThree.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddThree.setText("3");
        btnAddThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddThreeActionPerformed(evt);
            }
        });

        btnAddSix.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddSix.setText("6");
        btnAddSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSixActionPerformed(evt);
            }
        });

        btnAddNine.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddNine.setText("9");
        btnAddNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNineActionPerformed(evt);
            }
        });

        btnAddComma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddComma.setText(",");
        btnAddComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommaActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnSubtract.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCalculate.setText("=");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClear.setText("Limpar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddFour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddFive)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddSix))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddTwo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddThree))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddSeven)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddEight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddNine))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddZero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddComma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddSeven)
                            .addComponent(btnAddEight)
                            .addComponent(btnAddNine)
                            .addComponent(btnAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddFour)
                            .addComponent(btnAddFive)
                            .addComponent(btnAddSix)
                            .addComponent(btnSubtract))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddOne)
                            .addComponent(btnAddTwo)
                            .addComponent(btnAddThree)
                            .addComponent(btnMultiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddZero)
                            .addComponent(btnAddComma)
                            .addComponent(btnDivide)))
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOneActionPerformed
        adicionarValor(btnAddOne);
        clearFinalResult(btnAddOne);
    }//GEN-LAST:event_btnAddOneActionPerformed

    private void btnAddTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTwoActionPerformed
        adicionarValor(btnAddTwo);
        clearFinalResult(btnAddTwo);
    }//GEN-LAST:event_btnAddTwoActionPerformed

    private void btnAddThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddThreeActionPerformed
        adicionarValor(btnAddThree);
        clearFinalResult(btnAddThree);
    }//GEN-LAST:event_btnAddThreeActionPerformed

    private void btnAddFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFourActionPerformed
        adicionarValor(btnAddFour);
        clearFinalResult(btnAddFour);
    }//GEN-LAST:event_btnAddFourActionPerformed

    private void btnAddFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFiveActionPerformed
        adicionarValor(btnAddFive);
        clearFinalResult(btnAddFive);
    }//GEN-LAST:event_btnAddFiveActionPerformed

    private void btnAddSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSixActionPerformed
        adicionarValor(btnAddSix);
        clearFinalResult(btnAddSix);
    }//GEN-LAST:event_btnAddSixActionPerformed

    private void btnAddSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSevenActionPerformed
        adicionarValor(btnAddSeven);
        clearFinalResult(btnAddSeven);
    }//GEN-LAST:event_btnAddSevenActionPerformed

    private void btnAddEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEightActionPerformed
        adicionarValor(btnAddEight);
        clearFinalResult(btnAddEight);
    }//GEN-LAST:event_btnAddEightActionPerformed

    private void btnAddNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNineActionPerformed
        adicionarValor(btnAddNine);
        clearFinalResult(btnAddNine);
    }//GEN-LAST:event_btnAddNineActionPerformed

    private void btnAddZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddZeroActionPerformed
        adicionarValor(btnAddZero);
        clearFinalResult(btnAddZero);
    }//GEN-LAST:event_btnAddZeroActionPerformed

    private void btnAddCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommaActionPerformed
        adicionarValor(btnAddComma);
    }//GEN-LAST:event_btnAddCommaActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        adicionarValor(btnAdd);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        adicionarValor(btnSubtract);
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        adicionarValor(btnMultiply);
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        adicionarValor(btnDivide);
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        showResult();
        fimDoCalculo = true;
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearResult();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_jPanel1KeyPressed

    private void txtResultKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultKeyPressed
        System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == 96){
            adicionarValorTeclado("0");
        }
    }//GEN-LAST:event_txtResultKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddComma;
    private javax.swing.JButton btnAddEight;
    private javax.swing.JButton btnAddFive;
    private javax.swing.JButton btnAddFour;
    private javax.swing.JButton btnAddNine;
    private javax.swing.JButton btnAddOne;
    private javax.swing.JButton btnAddSeven;
    private javax.swing.JButton btnAddSix;
    private javax.swing.JButton btnAddThree;
    private javax.swing.JButton btnAddTwo;
    private javax.swing.JButton btnAddZero;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables

    //Método que adiciona os números e operações no campo de texto
    private void adicionarValor(JButton button) {
        String valorAnterior = txtResult.getText();

        if (valorAnterior.equals("0")) {
            txtResult.setText("");
        }

        valorAnterior = txtResult.getText();

        String valor = button.getText();
        String novoValor = valorAnterior + "" + valor;
        txtResult.setText(novoValor);
    }
    
    //Método que vai adicionar o valor digitado no Result
    private void adicionarValorTeclado(String valor){
        String valorAnterior = txtResult.getText();

        if (valorAnterior.equals("0")) {
            txtResult.setText("");
        }
        
        valorAnterior = txtResult.getText();

        String novoValor = valorAnterior + "" + valor;
        txtResult.setText(novoValor);
    }

    //Método que vai "desmembrar" os valores digitados
    private float[] getValores() {
        float valoresFloat[] = new float[2];
        String valor = txtResult.getText();

        String sinais = "/*+-";
        String valoresString[] = valor.split("[" + Pattern.quote(sinais) + "]");

        valoresFloat[0] = Float.parseFloat(valoresString[0]);
        valoresFloat[1] = Float.parseFloat(valoresString[1]);

        return valoresFloat;
    }

    private float calculateResult() {
        float result = 0;

        String sinal = txtResult.getText();

        //Recebendo os números digitados
        float valores[] = getValores();
        float value_one = valores[0];
        float value_two = valores[1];

        //Verificando qual operação vai ser executada
        if (sinal.contains("+")) {
            result = Operations.add(value_one, value_two);

        } else if (sinal.contains("-")) {
            result = Operations.subtract(value_one, value_two);

        } else if (sinal.contains("*")) {
            result = Operations.multiply(value_one, value_two);

        } else if (sinal.contains("/")) {
            result = Operations.divide(value_one, value_two);
        }

        return result;
    }

    private void clearResult() {
        txtResult.setText("0");
    }

    //Método que vai limpar o RESULTADO FINAL e adicionar o novo número digitado
    private void clearFinalResult(JButton btn) {
        if (fimDoCalculo) {
            clearResult();
            adicionarValor(btn);
            fimDoCalculo = false;
        }
    }

    private void showResult() {
        float finalResult = calculateResult();
        clearResult();
        txtResult.setText("" + finalResult);
    }


}
